client_id: maxigauge-ce583f23-98c6-4353-84c8-e14f5830bbaf
topic_base: "pressure"
device_name: "MaxiGauge"
mqtt_broker: "localhost"
mqtt_port: 1883
mqtt_connection_timeout: 60

maxigauge_address: "TCPIP::192.168.1.101::8000::SOCKET"
interval: 1.0  # seconds
